### ISSUE TITLE
Report memory usage per byte to ssb/w1r3/memory

### ISSUE THREAD

**Issue by coryan** [googleapis/storage-shared-benchmarking#121]
We want to know how much memory is allocated by the client to perform an operation. We should scale this by the number of bytes transferred.  For example, if to transfer 128MiB the client allocates (temporarily) 256MiB, we would report this as 2.0.  Whether the client does this in one single giant 256MiB allocation, or in 256 allocations of 1MiB (which are maybe released as it stops using them) we would still report 2.0.

- [x] C++
- [x] Go
- [ ] Java

PS: we may change our minds about this idea.

**Comment by BenWhitehead** [comment]
Java implementation: https://github.com/googleapis/storage-shared-benchmarking/pull/117
