### ISSUE TITLE
[w1r3/java] Tasks restart very often in Java

### ISSUE THREAD

**Issue by coryan** [googleapis/storage-shared-benchmarking#160]
Sometimes the Java tasks restart in a matter of hours, while C++ and Go tasks run for multiple days.

Compare

 https://screenshot.googleplex.com/QV4y8y2rZFJa3cX.png 

vs.

https://screenshot.googleplex.com/APcEPSkiLJSmqPT.png
https://screenshot.googleplex.com/JqrWCubrgaDZ8Vv.png

**Comment by BenWhitehead** [comment]
Fixed by https://github.com/googleapis/storage-shared-benchmarking/pull/162
